TrainingArguments:
  num_train_epochs: 1                  
  per_device_train_batch_size: 4       
  warmup_steps: 500                    
  weight_decay: 0.01                  
  logging_steps: 1                   
  learning_rate: 1e-5
  gradient_accumulation_steps: 2
  max_steps: 1
