artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  dataset_name: knkarthick/dialogsum
  local_data_file: artifacts/data_ingestion/DialogSum
  


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  local_data_file: artifacts/data_ingestion/DialogSum
  ALL_REQUIRED_FILES: ['train', 'validation', 'test']
  REQUIRED_FEATURES: ['id', 'dialogue', 'summary', 'topic']



data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/DialogSum
  tokenizer_name: google/flan-t5-base




model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/DialogSum
  model_ckpt: google/flan-t5-base




model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/DialogSum
  model_path: artifacts/model_trainer/flant5-dialogsum-model
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv