artifacts_root: artifacts

data_ingestion: 
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/SaadBens/Datasets/raw/main/samsum-dataset.zip
  local_data_file: artifacts/data_ingestion/samsum-dataset.zip
  unzip_dir: artifacts/data_ingestion
